### ISSUE TITLE
Make character walking animation stop when menu is open

### ISSUE THREAD

**Issue by warpfox** [warpfox/EB-Clone#10]

**Comment by VirtuaBoza** [comment]
@warpfox I thought you already fixed this.

**Comment by warpfox** [comment]
Nah. I don't know if I can do it through code, but I might be able to in Unity's Animator settings.

**Comment by VirtuaBoza** [comment]
Sure you could. just need to ensure that as long as you're paused, the Animate method always sets
bodyAnimator.SetInteger("horizontalMovement", 0);
bodyAnimator.SetInteger("verticalMovement", 0);

**Comment by warpfox** [comment]
GameManager pause function fixed this issue.
