### ISSUE TITLE
Integrate "pause" mechanic in overworld any time menu is open

### ISSUE THREAD

**Issue by warpfox** [warpfox/EB-Clone#11]
For instance, opening the pop-up menu will cause the game to pause; no animations or movement by characters, NPCs, enemies, environment, etc.

**Comment by VirtuaBoza** [comment]
This is usually done in unity by manipulating [time](https://docs.unity3d.com/ScriptReference/Time-timeScale.html). You set it to 0 I think.

**Comment by warpfox** [comment]
Created a GameManager class that handles this. This also fixed the animation problem, as when Time.timeScale is set to 0, animations cease until time resumes.
